[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/cloudinaried/:height/:image"
  to = "https://res.cloudinary.com/philhawksworth/image/fetch/q_auto,f_auto,h_:height/https://petsof.netlify.com/images/:image"
  status = 200


[[redirects]]
  from = "/cloudinaried/*"
  to = "/images/:splat"
  status = 404
